# -*- coding: utf-8 -*-
"""Data Mining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h24z5d-sKbzUuBkCDL8Eg3TJbOUURCoZ

Import Dataset
"""

import os

path_extract = "/content/drive/MyDrive/datamining/data"
os.makedirs(path_extract, exist_ok=True)

# print name folder join /Radiography
for folder in os.listdir(os.path.join(path_extract,"Radiography")):
    print(folder)

import os
import math
import random
from typing import List, Tuple, Dict
from PIL import Image

# =========================================================
# Utilities
# =========================================================

def set_seed(seed=42):
    random.seed(seed)

def clamp(x, lo, hi):
    return lo if x < lo else hi if x > hi else x

def mean(xs):
    return sum(xs) / (len(xs) if xs else 1)

def stdev(xs):
    if len(xs) < 2:
        return 1.0
    m = mean(xs)
    v = sum((x - m) ** 2 for x in xs) / (len(xs) - 1)
    return math.sqrt(v) if v > 1e-12 else 1.0

# =========================================================
# Image Loading & Preprocessing
# =========================================================

def list_image_files(folder):
    return sorted([
        os.path.join(folder, f)
        for f in os.listdir(folder)
        if f.lower().endswith((".jpg", ".png", ".jpeg"))
    ])

def load_image_grayscale_01(path):
    img = Image.open(path).convert("L")
    w, h = img.size
    data = list(img.getdata())
    out = [[0.0]*w for _ in range(h)]
    i = 0
    for y in range(h):
        for x in range(w):
            out[y][x] = data[i] / 255.0
            i += 1
    return out

def resize_bilinear(img, new_h, new_w):
    h, w = len(img), len(img[0])
    out = [[0.0]*new_w for _ in range(new_h)]
    ys = (h-1)/(new_h-1) if new_h > 1 else 0
    xs = (w-1)/(new_w-1) if new_w > 1 else 0

    for y2 in range(new_h):
        y = y2 * ys
        y0 = int(y); y1 = min(y0+1, h-1)
        wy = y - y0
        for x2 in range(new_w):
            x = x2 * xs
            x0 = int(x); x1 = min(x0+1, w-1)
            wx = x - x0
            v = (
                img[y0][x0]*(1-wx)*(1-wy) +
                img[y0][x1]*wx*(1-wy) +
                img[y1][x0]*(1-wx)*wy +
                img[y1][x1]*wx*wy
            )
            out[y2][x2] = v
    return out

def preprocess(img, size=(64,64)):
    img = resize_bilinear(img, size[0], size[1])
    flat = [v for r in img for v in r]
    m, s = mean(flat), stdev(flat)
    return [[(v-m)/s for v in r] for r in img]

# =========================================================
# HOG Feature
# =========================================================

def hog_features(img, cell=8, bins=9):
    h, w = len(img), len(img[0])
    gx = [[0]*w for _ in range(h)]
    gy = [[0]*w for _ in range(h)]

    for y in range(h):
        for x in range(w):
            gx[y][x] = img[y][min(x+1,w-1)] - img[y][max(x-1,0)]
            gy[y][x] = img[min(y+1,h-1)][x] - img[max(y-1,0)][x]

    nc_y, nc_x = h//cell, w//cell
    hist = [[[0]*bins for _ in range(nc_x)] for _ in range(nc_y)]
    bw = 180/bins

    for cy in range(nc_y):
        for cx in range(nc_x):
            for y in range(cy*cell,(cy+1)*cell):
                for x in range(cx*cell,(cx+1)*cell):
                    mag = math.sqrt(gx[y][x]**2 + gy[y][x]**2)
                    ang = math.degrees(math.atan2(gy[y][x],gx[y][x]))%180
                    b = int(ang/bw)%bins
                    hist[cy][cx][b] += mag

    feat=[]
    for y in range(nc_y-1):
        for x in range(nc_x-1):
            block=[]
            for dy in range(2):
                for dx in range(2):
                    block.extend(hist[y+dy][x+dx])
            norm = math.sqrt(sum(v*v for v in block))+1e-6
            feat.extend([v/norm for v in block])
    return feat

def to_features(X):
    return [hog_features(img) for img in X]

# =========================================================
# SVM RBF (Simplified SMO)
# =========================================================

def rbf(x,z,g):
    return math.exp(-g*sum((a-b)**2 for a,b in zip(x,z)))

class SVM:
    def __init__(self,C=1.0,gamma=0.01,passes=2):
        self.C=C; self.gamma=gamma; self.passes=passes

    def fit(self,X,y):
        self.X=X; self.y=y
        m=len(X)
        self.a=[0.0]*m; self.b=0
        for _ in range(self.passes):
            for i in range(m):
                Ei=sum(self.a[k]*y[k]*rbf(X[k],X[i],self.gamma) for k in range(m))+self.b-y[i]
                if y[i]*Ei<-1e-3 and self.a[i]<self.C:
                    j=random.randrange(m)
                    Ej=sum(self.a[k]*y[k]*rbf(X[k],X[j],self.gamma) for k in range(m))+self.b-y[j]
                    ai,aj=self.a[i],self.a[j]
                    eta=2*rbf(X[i],X[j],self.gamma)-rbf(X[i],X[i],self.gamma)-rbf(X[j],X[j],self.gamma)
                    if eta>=0: continue
                    ajn=aj-y[j]*(Ei-Ej)/eta
                    ajn=clamp(ajn,0,self.C)
                    ain=ai+y[i]*y[j]*(aj-ajn)
                    self.a[i]=ain; self.a[j]=ajn
        return self

    def predict(self,X):
        out=[]
        for x in X:
            s=sum(self.a[k]*self.y[k]*rbf(self.X[k],x,self.gamma) for k in range(len(self.X)))+self.b
            out.append(1 if s>=0 else -1)
        return out

# =========================================================
# Metrics
# =========================================================

def f1(y,p):
    tp=tn=fp=fn=0
    for a,b in zip(y,p):
        if a==1 and b==1: tp+=1
        elif a==-1 and b==-1: tn+=1
        elif a==-1 and b==1: fp+=1
        else: fn+=1
    prec=tp/(tp+fp) if tp+fp else 0
    rec=tp/(tp+fn) if tp+fn else 0
    f1=2*prec*rec/(prec+rec) if prec+rec else 0
    acc=(tp+tn)/(tp+tn+fp+fn)
    return acc,f1

# =========================================================
# Pipeline
# =========================================================

def load_split(root,split):
    X=[]; y=[]
    for cls,lbl in [("NORMAL",-1),("PNEUMONIA",1)]:
        for fp in list_image_files(os.path.join(root,split,cls)):
            img=preprocess(load_image_grayscale_01(fp))
            X.append(img); y.append(lbl)
    return X,y

def run_pipeline(root):
    print("LOAD DATA")
    Xtr,ytr=load_split(root,"train")
    Xva,yva=load_split(root,"val")
    Xte,yte=load_split(root,"test")

    print("HOG EXTRACTION")
    Xtrf=to_features(Xtr+Xva)
    ypool=ytr+yva

    best=(0,0,0)
    for C in [0.5,1.0]:
        for g in [1e-3,1e-2]:
            print(f"TRAIN C={C} gamma={g}")
            svm=SVM(C,g).fit(Xtrf,ypool)
            acc,f1s=f1(ypool,svm.predict(Xtrf))
            print(" f1 =",f1s)
            if f1s>best[2]:
                best=(C,g,f1s)

    print("BEST:",best)

    print("FINAL TEST")
    svm=SVM(best[0],best[1]).fit(Xtrf,ypool)
    Xtef=to_features(Xte)
    print("TEST:",f1(yte,svm.predict(Xtef)))

# =========================================================
# RUN
# =========================================================

root = os.path.join(path_extract,"Radiography")
run_pipeline(root)

def train_model(
    dataset_path: str,
    image_size=(64, 64),
    C_values=[0.5, 1.0],
    gamma_values=[1e-3, 1e-2],
    seed=42
):
    """
    dataset_path : path ke folder Radiography
    """

    set_seed(seed)

    # ===============================
    # Load Dataset
    # ===============================
    print("LOAD DATASET FROM:", dataset_path)

    Xtr, ytr = load_split(dataset_path, "train")
    Xva, yva = load_split(dataset_path, "val")
    Xte, yte = load_split(dataset_path, "test")

    print(f"Train: {len(Xtr)} | Val: {len(Xva)} | Test: {len(Xte)}")

    # ===============================
    # Feature Extraction (HOG)
    # ===============================
    print("EXTRACT HOG FEATURES")

    Xtrf = to_features(Xtr + Xva)
    ypool = ytr + yva

    # ===============================
    # Hyperparameter Search
    # ===============================
    best_C = None
    best_gamma = None
    best_f1 = 0

    for C in C_values:
        for gamma in gamma_values:
            print(f"TRAIN SVM | C={C} | gamma={gamma}")
            svm = SVM(C=C, gamma=gamma).fit(Xtrf, ypool)

            acc, f1_score = f1(ypool, svm.predict(Xtrf))
            print(f"  Acc={acc:.4f} | F1={f1_score:.4f}")

            if f1_score > best_f1:
                best_f1 = f1_score
                best_C = C
                best_gamma = gamma

    print("\nBEST PARAMETER")
    print("C =", best_C)
    print("gamma =", best_gamma)
    print("F1 =", best_f1)

    # ===============================
    # Final Evaluation on Test Set
    # ===============================
    print("\nFINAL TEST EVALUATION")

    svm = SVM(C=best_C, gamma=best_gamma).fit(Xtrf, ypool)
    Xtef = to_features(Xte)

    acc_test, f1_test = f1(yte, svm.predict(Xtef))
    print(f"TEST ACC = {acc_test:.4f}")
    print(f"TEST F1  = {f1_test:.4f}")

    return {
        "C": best_C,
        "gamma": best_gamma,
        "f1_val": best_f1,
        "acc_test": acc_test,
        "f1_test": f1_test
    }
